### PR TITLE
Test 1 Attempt 6: single file, correct ID

### PR DESCRIPTION
**Pull request by maciejpedzich**
Ok, so basically my bot had previously been trying to merge changes into Mack's repo, hahaha. Anyway, now that I've figured it out, I should see the bot merge the changes into the right repo... fingers crossed!

### CODE REVIEW

**Comment by maciejpedzich** [comment]
Ah, so I actually changed the test entry to an invalid string, hahaha. But hey, @mackorone, you should check this out!

**Comment by mackorone** [comment]
This is awesome! If possible, I'd prefer to disable the "auto merge" behavior because I don't want anyone spamming the repo with thousands of new playlists, but having automation validation would be really useful!

How do I integrate this bot with my repo? Where is the source code?

**Comment by maciejpedzich** [comment]
>I'd prefer to disable the "auto merge" behavior because I don't want anyone spamming the repo with thousands of new playlists, but having automation validation would be really useful!

Sure, no problem! What would you like the bot to do instead? Just ping you that the PR can safely be merged, or do you have something else in mind?

> How do I integrate this bot with my repo? Where is the source code?

The source code is [right here](https://github.com/maciejpedzich/mackorone-playlist-pr-bot). As for integrating with the repo, I'll email you the GitHub app link in a minute!

**Comment by mackorone** [comment]
> Just ping you that the PR can safely be merged

Yep, that would be perfect! Perhaps something like:
1. Is this a valid playlist?
2. If so, what's its name, who's the owner, and how many followers does it have?

> I'll email you the GitHub app link in a minute

Sounds good, thanks!

**Comment by maciejpedzich** [comment]
> > Just ping you that the PR can safely be merged
> 
> Yep, that would be perfect! Perhaps something like:
> 
> 1. Is this a valid playlist?
> 2. If so, what's its name, who's the owner, and how many followers does it have?
> 
> > I'll email you the GitHub app link in a minute
> 
> Sounds good, thanks!

Cool, thanks for replying! I'll code up the changes and you should get notified via the bot comment.

**Pull request merged**
